### ISSUE TITLE
Fail meteor build

### ISSUE THREAD

**Issue by kevrat** [Akryum/vue-meteor#157]
I use meteor-now to deploy. But it gives error

> meteor-now -e METEOR_SETTINGS=@meteor-settings -e MONGO_URL=*** -e ROOT_URL=*** -d
> [METEOR-NOW] - running command: meteor build .meteor/local/builds --server-only --architecture=os.linux.x86_64
> 
> WARNING: The output directory is under your source tree.
>          Your generated files may get interpreted as source code!
>          Consider building into a different directory instead
>          meteor build ../output
> 
> Errors prevented bundling:
> While loading plugin `vue-component` from package `akryum:vue-component`:
> native: Unexpected token /
> at Object.parse (native)
> at getVueVersion (packages/vue-component/plugin/vue-compiler.js:17:22)
> at meteorInstall.node_modules.meteor.vue-component.plugin.vue-compiler.js (packages/vue-component/plugin/vue-compiler.js:35:20)
> at fileEvaluate (packages/modules-runtime.js:188:9)
> at require (packages/modules-runtime.js:111:16)
> at <runJavaScript-13>:20426:1
> at <runJavaScript-13>:20433:3
> 
> 
> Possibly unhandled Error: 1
>     at Promise$_rejecter (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:590:44)
>     at C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\index.js:85:13
>     at tryCatch1 (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\util.js:63:19)
>     at Promise$_callHandler [as _callHandler] (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:695:13)
>     at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:7
> 11:18)
>     at Promise$_settlePromiseAt [as _settlePromiseAt] (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:868:14)
>     at Promise$_settlePromises [as _settlePromises] (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:1006:14)
>     at Promise$_rejectPromises [as _rejectPromises] (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:999:10)
>     at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\async.js:74:12)
>     at Async$consumeFunctionBuffer (C:\Users\kevrat\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\async.js:37:14)

My packages file

> meteor-base@1.0.4             # Packages every Meteor app needs to have
> mobile-experience@1.0.4       # Packages for a great mobile UX
> mongo@1.1.16                   # The database Meteor supports right now
> reactive-var@1.0.11            # Reactive variable for tracker
> tracker@1.1.2                 # Meteor's client-side reactive programming library
> 
> standard-minifier-css@1.3.4   # CSS minifier run for production mode
> es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
> ecmascript@0.6.3              # Enable ECMAScript2015+ syntax in app code
> shell-server@0.2.3            # Server-side component of the `meteor shell` command
> 
> static-html
> akryum:vue-component@0.8.15
> mrt:accounts-vk
> service-configuration
> accounts-facebook
> jagi:astronomy
> jagi:astronomy-timestamp-behavior
> akryum:vue-blaze-template
> akryum:vue-router2
> meteorhacks:fast-render

package.json deps
 

>  "dependencies": {
>     "babel-runtime": "^6.23.0",
>     "meteor-node-stubs": "~0.2.4",
>     "onsenui": "^2.2.1",
>     "vue": "^2.2.6",
>     "vue-meta": "^0.5.5",
>     "vue-meteor-tracker": "^1.2.0",
>     "vue-onsenui": "^2.0.0-beta.0",
>     "vue-router": "^2.3.1"
>   },
>   "devDependencies": {
>     "babel-eslint": "^7.2.1",
>     "eslint": "^3.18.0",
>     "eslint-config-airbnb": "^14.1.0",
>     "eslint-import-resolver-meteor": "^0.3.4",
>     "eslint-plugin-import": "^2.2.0",
>     "eslint-plugin-jsx-a11y": "^4.0.0",
>     "eslint-plugin-meteor": "^4.0.1",
>     "eslint-plugin-react": "^6.10.3"
>   }

It is possible to solve?

**Comment by kevrat** [comment]
It is my fault. I have some comments in my package.json. After removing it is not throw this error
