### ISSUE TITLE
vue-component@0.8.18 Compile issue

### ISSUE THREAD

**Issue by lunatolun** [Akryum/vue-meteor#161]
Meteor packages
```
akryum:vue-component
akryum:vue-blaze-template
```

Versions
`akryum:vue-component@0.8.18`

NPM packages
   
```
    "vue": "^2.2.6",
    "vue-meteor-tracker": "^1.2.1",
    "vue-router": "^2.5.1",
    "vuex": "^2.3.1"
```
Using akryum:vue-component@0.8.17 fixes it

**Comment by Akryum** [comment]
What is the issue exactly?

**Comment by lunatolun** [comment]
```
(.meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:881:17)
   at iterateeCallback
   (.meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:866:17)
   at
   .meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:843:16
   at packages/vue-component/plugin/vue-compiler.js:75:11
   at
   .meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3025:16
   at replenish
   (.meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:881:17)
   at iterateeCallback
   (.meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:866:17)
   at
   .meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:843:16
   at packages/vue-component/plugin/vue-compiler.js:75:11
   at
   .meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3025:16
   at replenish
   (.meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:881:17)
   at
   .meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:885:9
   at Object.eachLimit$1
   (.meteor/packages/akryum_vue-component/.0.8.18.8z2w6i++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3114:22)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:42:11)
```

**Comment by Akryum** [comment]
Could you paste the full console trace please? :smile:

**Comment by Akryum** [comment]
Could you try with the latest release?

**Comment by lunatolun** [comment]
No issues with the latest release
