### ISSUE TITLE
Error after update from 0.8.15 to 0.8.18

### ISSUE THREAD

**Issue by nizulzaim** [Akryum/vue-meteor#166]
Hi, it look i have error after update to latest version and related vue-component-dev-server. This error will not happen if running in production but problem if run in development env.

``` bash
W20170426-05:57:36.243(8)? (STDERR) /home/nizul/.meteor/packages/meteor-tool/.1.5.0-beta.13.d67rzw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20170426-05:57:36.299(8)? (STDERR) 						throw(ex);
W20170426-05:57:36.300(8)? (STDERR) 						^
W20170426-05:57:36.300(8)? (STDERR) 
W20170426-05:57:36.301(8)? (STDERR) TypeError: Cannot read property 'filter' of undefined
W20170426-05:57:36.301(8)? (STDERR)     at Object.Future.wait (/home/nizul/.meteor/packages/meteor-tool/.1.5.0-beta.13.d67rzw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20170426-05:57:36.302(8)? (STDERR)     at packages/meteor.js:213:24
W20170426-05:57:36.302(8)? (STDERR)     at meteorInstall.node_modules.meteor.akryum:vue-component-dev-server.server.main.js (packages/akryum:vue-component-dev-server/server/main.js:23:73)
W20170426-05:57:36.303(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170426-05:57:36.304(8)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170426-05:57:36.304(8)? (STDERR)     at /home/nizul/Project/fitness-trainer/.meteor/local/build/programs/server/packages/akryum_vue-component-dev-server.js:99:15
W20170426-05:57:36.305(8)? (STDERR)     at /home/nizul/Project/fitness-trainer/.meteor/local/build/programs/server/packages/akryum_vue-component-dev-server.js:105:3
W20170426-05:57:36.305(8)? (STDERR)     at /home/nizul/Project/fitness-trainer/.meteor/local/build/programs/server/boot.js:338:34
W20170426-05:57:36.306(8)? (STDERR)     at Array.forEach (native)
W20170426-05:57:36.306(8)? (STDERR)     at Function._.each._.forEach (/home/nizul/.meteor/packages/meteor-tool/.1.5.0-beta.13.d67rzw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170426-05:57:36.307(8)? (STDERR)     - - - - -
W20170426-05:57:36.308(8)? (STDERR)     at module.exports.getIpV4AddressForInterface (/home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/local-ipv4-address/detectors/ifconfig.js:6:32)
W20170426-05:57:36.308(8)? (STDERR)     at _fulfilled (/home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/q/q.js:854:54)
W20170426-05:57:36.309(8)? (STDERR)     at self.promiseDispatch.done (/home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/q/q.js:883:30)
W20170426-05:57:36.309(8)? (STDERR)     at Promise.promise.promiseDispatch (/home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/q/q.js:816:13)
W20170426-05:57:36.310(8)? (STDERR)     at /home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/q/q.js:624:44
W20170426-05:57:36.310(8)? (STDERR)     at runSingle (/home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/q/q.js:137:13)
W20170426-05:57:36.310(8)? (STDERR)     at flush (/home/nizul/.meteor/packages/akryum_vue-component-dev-server/.0.0.7.1gfalh7++os+web.browser+web.cordova/npm/node_modules/q/q.js:125:13)
W20170426-05:57:36.311(8)? (STDERR)     at nextTickCallbackWith0Args (node.js:489:9)
W20170426-05:57:36.311(8)? (STDERR)     at process._tickCallback (node.js:418:13)

``

**Comment by Akryum** [comment]
Could you please try again with the latest `0.9.0` release?
