### ISSUE TITLE
akryum:vue-component will automatically parse .vue files under node_module and import it

### ISSUE THREAD

**Issue by zhongqf** [Akryum/vue-meteor#178]
After using `meteor npm install element-ui --save` (and this is the only command I run) to import ElementUI into Meteor project, Meteor can not startup properly. It gives something like this: 
```

=> Started MongoDB.
W20170502-22:17:53.069(8)? (STDERR) /.meteor/local/build/programs/server/packages/modules.js:927
W20170502-22:17:54.449(8)? (STDERR) import Vue from 'vue';
W20170502-22:17:54.450(8)? (STDERR) ^^^^^^
W20170502-22:17:54.451(8)? (STDERR)
W20170502-22:17:54.452(8)? (STDERR) SyntaxError: Unexpected reserved word
W20170502-22:17:54.453(8)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170502-22:17:54.453(8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:297:30
W20170502-22:17:54.454(8)? (STDERR)     at Array.forEach (native)
W20170502-22:17:54.454(8)? (STDERR)     at Function._.each._.forEach (/.meteor/packages/meteor-tool/.1.4.4_1.ecfm4z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170502-22:17:54.455(8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:128:5
W20170502-22:17:54.456(8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:352:5
W20170502-22:17:54.456(8)? (STDERR)     at Function.run /.meteor/local/build/programs/server/profile.js:510:12)
W20170502-22:17:54.457(8)? (STDERR)     at /.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1

```

It looks that, even I was not importing element-ui in application code,
`akryum:vue-component` will parse every `.vue` files under `node_module`
and import them as a component. It is weird.

**Comment by zhongqf** [comment]
Sorry. A `.vueignore` file will solve this.
