### ISSUE TITLE
meteor-vue-electron app problem

### ISSUE THREAD

**Issue by OpsSingular** [Akryum/vue-meteor#90]
Hi, 

I was trying my luck at creating a meteor-vue-electron app using https://github.com/arboleya/electrify. However i get the below error in one of the plugins. Any help to move forward is appreciated.

```
  While processing files with akryum:vue-component (for target
   web.browser):
   packages/vue-component/plugin/vue-compiler.js:189:9: Cannot read
   property '__addStyle' of undefined
   at VueCompo.addCompileResult
   (packages/vue-component/plugin/vue-compiler.js:189:9)
   at packages/vue-component/plugin/vue-compiler.js:97:16
```
in the below file
https://github.com/Akryum/meteor-vue-component/blob/61ce8d1102dc8b19f052545817d5503fce5cad00/packages/vue-component/plugin/vue-compiler.js

at line 189

Steps to reproduce

1. Meteor Create sampleappname
2. cd sampleappname
3. meteor npm install
4. meteor add akryum:vue-component 
5. npm install -g electrify
6. electrify

**Comment by nizulzaim** [comment]
I can confirm this error when using electrify. When running in Visual Studio Code Meteor CLI helper (packages) also give some error. However @AdityaDinesh , if you need to develop desktop application, i recommend you to use meteor-desktop to compile it [Meteor Desktop](https://github.com/wojtkowiak/meteor-desktop)

**Comment by nizulzaim** [comment]
You can see the same error 'addStyle' of undefined from Visual Studio Code

```
--------------------------------------------------------------------------------------------------
MeteorHelper: executing 'meteor run --port 3000'..
--------------------------------------------------------------------------------------------------
[[[[[ ~\z\DevsignStudio\peper-boilerplate ]]]]]

=> Started proxy.
[TypeError: process.stdout.clearLine is not a function]
=> Errors prevented startup:
   
   While processing files with akryum:vue-component (for target
   web.browser):
   packages/vue-component/plugin/vue-compiler.js:189:9: Cannot read
   property '__addStyle' of undefined
   at VueCompo.addCompileResult
   (packages/vue-component/plugin/vue-compiler.js:189:9)
   at packages/vue-component/plugin/vue-compiler.js:97:16
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:101:11
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\skyni\AppData\Local\.meteor\packages\akryum_vue-component\0.7.7\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:221:35)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:68:11)
   
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.

```

**Comment by Akryum** [comment]
Hot-reloading is not supported in electron yet.

**Comment by mwarren2** [comment]
I don't use electron, but I get the same problem. 
It's not electron causing this.

**Comment by mwarren2** [comment]
Actually the problem has now gone. Sorry for the bother.

I just removed and reinstalled vue-component and now it has vanished...

**Comment by nizulzaim** [comment]
This error already not show up but have another error (same error from issue #126)
